# Fly.io configuration for the Cosmic Helix renderer.
# Update the `app` value before deploying to avoid collisions.
app = "stone-grimoire-helix"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile.fly"

[env]
  NODE_ENV = "production"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
