name: ND-safe linter

on:
  push:
    branches: ["main"]
  pull_request:
  workflow_dispatch:

jobs:
  nd-safe:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run ND-safe checks
        run: node --test tests/nd-safe.test.js
